export const SET_INGREDIENT = 'SET_INGREDIENT';
export const FETCH_INGREDIENT_FAIL = 'FETCH_INGREDIENT_FAIL';
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';

export const PURCHASE_BURGER_ONLOAD = 'PURCHASE_BURGER_ONLOAD';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_END = 'PURCHASE_BURGER_END';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
